from models.hotel import HotelResult, HotelResults
from models.flight import FlightResult, FlightResults
from langchain_core.messages import HumanMessage
from agents.team import TripPlanningState

mock_state : TripPlanningState = {
    "messages" : [HumanMessage("Tôi muốn lên kế hoạch một chuyến đi phiêu lưu cho hai người từ Hà Nội đến Đà nẵng, đi từ ngày 02/10/2025 đến 06/10/2025. Ngân sách của chúng tôi là 10 triệu đồng. Một người trong chúng tôi ăn chay, nhưng cả hai đều thích thử đặc sản địa phương. Về chỗ ở, chúng tôi chỉ cần một homestay sạch sẽ, có phòng riêng và view đẹp.")],

    'hotel_options': HotelResults(hotels=[HotelResult(hotel_name='Ha Giang Vegetarian Homestay', price='240,000 VND per night', rating='8.3', address='Ha Giang, Vietnam', amenities=['Free breakfast', 'Free cancellation', 'Vegetarian-friendly'], description='A cozy homestay offering vegetarian meals and a friendly atmosphere.', url='https://www.kayak.com/hotels/Ha-Giang-Vegetarian-Homestay,Ha-Giang-p2631332-h1072082236-details/2025-10-02/2025-10-06/2adults?psid=uHCEClmeOr&pm=nightly-base')]),

    'flight_options': FlightResults(flights=[FlightResult(price='4870080 VND', airline='Vietravel Airlines', departure_time='6:25 AM on Thu, Oct 2', arrival_time='7:45 AM on Thu, Oct 2', duration='1 hr 20 min', stops=0), FlightResult(price='5561280 VND', airline='Vietjet', departure_time='5:30 AM on Mon, Oct 6', arrival_time='6:50 AM on Mon, Oct 6', duration='1 hr 20 min', stops=0)]),

    'destination': ('# Tourist Guide\n'
                '\n'
                '## Main Attractions\n'
                '1. **My Khe Beach**\n'
                '   - **Description:** A beautiful beach known for its white '
                'sand and clear waters, perfect for sunbathing and water '
                'sports.\n'
                '   - **Location:** Da Nang, Vietnam\n'
                '   - **Opening Hours:** Open year-round\n'
                '   - **Entrance Fees:** Free\n'
                '   - **Visit Duration:** 2-4 hours\n'
                '   - **Visitor Tips:** Arrive early to secure a good spot and '
                'consider renting a beach chair.\n'
                '\n'
                '2. **Marble Mountains**\n'
                '   - **Description:** A cluster of five marble and limestone '
                'hills with caves, tunnels, and Buddhist sanctuaries.\n'
                '   - **Location:** Hoa Hai, Da Nang\n'
                '   - **Opening Hours:** 7:00 AM - 5:30 PM\n'
                '   - **Entrance Fees:** Approximately 40,000 VND\n'
                '   - **Visit Duration:** 2-3 hours\n'
                '   - **Visitor Tips:** Wear comfortable shoes for climbing '
                'and bring water.\n'
                '\n'
                '3. **Dragon Bridge**\n'
                '   - **Description:** A stunning bridge that breathes fire '
                'and water on weekends, symbolizing Da Nang’s growth.\n'
                '   - **Location:** Tran Hung Dao, Da Nang\n'
                '   - **Opening Hours:** Open year-round\n'
                '   - **Entrance Fees:** Free\n'
                '   - **Visit Duration:** 30 minutes\n'
                '   - **Visitor Tips:** Visit at night to see the bridge lit '
                'up.\n'
                '\n'
                '## Common Activities\n'
                '- **Local Food Tours:** Explore Da Nang’s culinary scene, '
                'including local specialties like Mi Quang (Quang noodles) and '
                'seafood.\n'
                '- **Beach Activities:** Enjoy swimming, sunbathing, or trying '
                'out water sports like jet skiing and parasailing.\n'
                '- **Cultural Visits:** Visit local temples and pagodas, such '
                'as Linh Ung Pagoda, for a glimpse into Vietnamese '
                'spirituality.\n'
                '\n'
                '## Popular Areas\n'
                '1. **Han River Area**\n'
                '   - **Description:** A vibrant area with restaurants, cafes, '
                'and a beautiful riverside promenade.\n'
                '   - **Highlights:** Great for evening strolls and dining '
                'with a view.\n'
                '\n'
                '2. **Old Town Hoi An (Day Trip)**\n'
                '   - **Description:** A UNESCO World Heritage site known for '
                'its well-preserved ancient town and lantern-lit streets.\n'
                '   - **Distance from Da Nang:** About 30 km\n'
                '   - **Transportation:** Buses and taxis available\n'
                '   - **Visit Duration:** 4-6 hours\n'
                '\n'
                '3. **Son Tra Peninsula**\n'
                '   - **Description:** A natural reserve with stunning views, '
                'hiking trails, and the famous Linh Ung Pagoda.\n'
                '   - **Location:** Da Nang\n'
                '   - **Visit Duration:** 2-3 hours\n'
                '\n'
                '## Basic Information\n'
                '- **General Visiting Tips:** \n'
                '  - Always carry cash, as some places may not accept cards.\n'
                '  - Respect local customs, especially when visiting temples.\n'
                '  \n'
                '- **Common Transportation Options:**\n'
                '  - **Flights:** Quickest option from Hanoi to Da Nang (1.5 '
                'hours).\n'
                '  - **Trains:** Scenic journey with beautiful views (14-17 '
                'hours).\n'
                '  - **Buses:** Budget-friendly option, but longer travel time '
                '(16-20 hours).\n'
                '  \n'
                '- **Standard Tourist Advice:**\n'
                '  - Book accommodations in advance, especially during peak '
                'seasons.\n'
                '  - Stay hydrated and wear sunscreen when exploring outdoor '
                'attractions.\n'
                '  \n'
                'With your budget of 10 million VND, you can enjoy a '
                'comfortable stay, indulge in local cuisine, and explore the '
                'beautiful sights of Da Nang. Enjoy your adventure!',),
    
    'budget': ('To optimize your travel budget for the adventure trip from Hanoi '
            "to Da Nang for two people from October 2 to October 6, 2025, let's "
            'break down the costs and see how we can stay within your budget of '
            '10 million VND.\n'
            '\n'
            '### 1. Analyze Total Budget and Cost Requirements\n'
            '\n'
            '#### Estimated Costs:\n'
            '- **Transportation:**\n'
            '  - **Flights (Hanoi to Da Nang):** Approximately 1,500,000 VND '
            'per person one way. For two people round trip: \n'
            '    - 1,500,000 VND x 2 x 2 = **6,000,000 VND**\n'
            '  - **Total Transportation Cost:** **6,000,000 VND**\n'
            '\n'
            '- **Accommodations:**\n'
            '  - **Hotel Option:** Ha Giang Vegetarian Homestay at 240,000 VND '
            'per night for 4 nights:\n'
            '    - 240,000 VND x 4 = **960,000 VND**\n'
            '\n'
            '- **Activities:**\n'
            '  - **Marble Mountains Entrance Fee:** 40,000 VND per person:\n'
            '    - 40,000 VND x 2 = **80,000 VND**\n'
            '  - **Local Food Tours and Beach Activities:** Estimated at '
            '**500,000 VND** for two people.\n'
            '\n'
            '- **Food:**\n'
            '  - **Daily Meals:** Estimated at 200,000 VND per person per day '
            'for 4 days:\n'
            '    - 200,000 VND x 2 x 4 = **1,600,000 VND**\n'
            '\n'
            '### Total Estimated Costs:\n'
            '- **Transportation:** 6,000,000 VND\n'
            '- **Accommodations:** 960,000 VND\n'
            '- **Activities:** 580,000 VND\n'
            '- **Food:** 1,600,000 VND\n'
            '\n'
            '**Total Estimated Cost:** 6,000,000 + 960,000 + 580,000 + '
            '1,600,000 = **9,140,000 VND**\n'
            '\n'
            '### 2. Budget Breakdown:\n'
            '- **Original Total Cost:** 9,140,000 VND\n'
            '- **Remaining Budget:** 10,000,000 VND - 9,140,000 VND = **860,000 '
            'VND**\n'
            '\n'
            '### 3. Suggestions for Cost-Saving Alternatives:\n'
            '- **Transportation:**\n'
            '  - If you book flights early, you might find discounts. Consider '
            'checking budget airlines for promotional fares.\n'
            '  \n'
            '- **Accommodations:**\n'
            '  - If you want to save more, consider looking for alternative '
            'homestays or guesthouses that might offer lower rates while still '
            'providing a clean and comfortable stay.\n'
            '\n'
            '- **Activities:**\n'
            '  - Explore free activities such as visiting My Khe Beach or '
            'Dragon Bridge, which can save you on entrance fees.\n'
            '\n'
            '- **Dining:**\n'
            '  - Look for local eateries or street food options that are '
            'vegetarian-friendly and offer local specialties at lower prices.\n'
            '\n'
            '### 4. Money-Saving Strategies:\n'
            '- **Early Booking Discounts:** Book flights and accommodations as '
            'soon as possible to secure the best rates.\n'
            '- **Package Deals:** Check for travel packages that include '
            'flights and accommodations for potential savings.\n'
            '- **Local Passes:** Research if there are any local tourist passes '
            'that provide discounts for multiple attractions.\n'
            '\n'
            '### Summary of Optimized Budget:\n'
            '- **Original Total Cost:** 9,140,000 VND\n'
            '- **Optimized Total Cost:** 9,140,000 VND (with potential savings '
            'if alternatives are chosen)\n'
            '- **Remaining Budget for Extras:** 860,000 VND\n'
            '\n'
            'This budget allows you to enjoy your trip comfortably while still '
            'having some flexibility for any unexpected expenses or additional '
            'activities. If you would like to explore specific alternatives or '
            'need further assistance, feel free to ask!',),
    
    'dining': ('# 🍽️ Restaurant Recommendations\n'
            '\n'
            '### 1. Ngoc Chi Vegetarian Restaurant\n'
            '- **Cuisine Type:** Vegetarian\n'
            '- **Price Range:** 30,000 – 80,000 VND (~$1.30 – $3.40)\n'
            '- **Rating:** Highly recommended for fresh ingredients\n'
            '- **Location:** [202 Hoang Dieu, Nam Duong, Hai Chau, Da '
            'Nang](https://maps.app.goo.gl/UMdHf7qYWZqWnY3n9)\n'
            '- **Operating Hours:** 7:00 AM – 9:00 PM (Peak hours at 5:00 PM)\n'
            '- **Dietary Options:** Vegetarian-friendly\n'
            '- **Special Features:** Dishes prepared from fresh, natural '
            'ingredients sourced from their own farm.\n'
            '- **Popular Dishes:** Fried rice, vegetarian hotpot.\n'
            '\n'
            '### 2. KURUMI Vegan Restaurant\n'
            '- **Cuisine Type:** Vegan\n'
            '- **Price Range:** 60,000 – 130,000 VND (~$2.60 – $5.60)\n'
            '- **Rating:** Known for friendly staff and good ambiance\n'
            '- **Location:** [My An area, Da '
            'Nang](https://maps.app.goo.gl/6TDSYryZ6DUfuvFe8)\n'
            '- **Operating Hours:** 8:00 AM – 9:30 PM\n'
            '- **Dietary Options:** Vegan-friendly\n'
            '- **Special Features:** Indoor and outdoor seating, free cold '
            'water.\n'
            '- **Popular Dishes:** Sandwich with smoked tofu, quinoa salad.\n'
            '\n'
            '### 3. Tinh Quan Vegetarian Restaurant\n'
            '- **Cuisine Type:** Vegetarian\n'
            '- **Price Range:** 20,000 – 200,000 VND (~$0.90 – $8.60)\n'
            '- **Rating:** Local favorite\n'
            '- **Location:** [11 Tran Nhat Duat, Tho Quang, Son Tra, Da '
            'Nang](https://maps.app.goo.gl/dJrUJgZTR5j5Ciri7)\n'
            '- **Operating Hours:** 6:15 AM – 9:00 PM\n'
            '- **Dietary Options:** Vegetarian-friendly\n'
            '- **Special Features:** Known for a wide variety of vegetarian '
            'dishes.\n'
            '\n'
            '# 🛍️ Food Markets & Culinary Experiences\n'
            '\n'
            '### 1. Con Market\n'
            '- **Specialties:** Fresh produce, seafood, and local street food.\n'
            '- **Best Visiting Times:** Morning for fresh produce, bustling '
            'atmosphere.\n'
            '- **Cultural Significance:** A hub for local life and a great '
            'place to experience Vietnamese culture.\n'
            '\n'
            '### 2. Han Market\n'
            '- **Specialties:** Souvenirs, tropical fruits, and local '
            'delicacies.\n'
            '- **Best Visiting Times:** Early morning or late afternoon.\n'
            '- **Cultural Significance:** Known as a must-visit for tourists to '
            'stock up on local goods.\n'
            '\n'
            '### 3. Bac My An Market\n'
            '- **Specialties:** A variety of local food at affordable prices.\n'
            '- **Best Visiting Times:** Lunch hours for the best food options.\n'
            '- **Cultural Significance:** Popular among locals for its hearty '
            'portions and tasty dishes.\n'
            '\n'
            '### Culinary Experiences\n'
            '- **Cooking Classes:** Consider joining a cooking class to learn '
            'how to prepare local dishes. Options include:\n'
            '  - **Jolie Da Nang Cooking Class with Organic Garden and Market '
            'Tour** - 39 USD\n'
            '  - **Vietnamese Home Cooking Class with Market Tour** - 37 USD\n'
            '- **Market Tours:** Experience local markets and learn about '
            'Vietnamese ingredients and cooking techniques.\n'
            '\n'
            '# ℹ️ Additional Information\n'
            '- **Local Customs:** Always carry cash, as some places may not '
            'accept cards. Respect local customs, especially in temples.\n'
            '- **Peak Hours:** Avoid dining during peak hours (around 5 PM) to '
            'enjoy a more relaxed experience.\n'
            '- **Transportation Options:** Grab taxis or local buses are '
            'convenient for getting around Da Nang.\n'
            '- **Safety Tips:** Stay hydrated and wear sunscreen when exploring '
            'outdoor attractions.\n'
            '\n'
            'With your budget of 10 million VND, you can enjoy a comfortable '
            'stay, indulge in local cuisine, and explore the beautiful sights '
            'of Da Nang. Enjoy your adventure! 🌏✈️',),

    'itinerary': ('**I. Executive Summary**\n'
                '\n'
                '- 🎯 **Trip Purpose & Vision**\n'
                "  - **Primary goals:** Adventure trip exploring Da Nang's "
                'natural beauty and local cuisine.\n'
                '  - **Special occasions:** None specified.\n'
                '  - **Key preferences:** Vegetarian-friendly options, local '
                'specialties, and a clean homestay with beautiful views.\n'
                '\n'
                '- ✈️ **Travel Overview**\n'
                '  - **Exact dates:** October 2 - October 6, 2025 (5 days)\n'
                '  - **Destinations:** Hanoi to Da Nang\n'
                '  - **Group composition:** 2 adults\n'
                '  - **Overall style:** Mid-range, focusing on comfort and local '
                'experiences.\n'
                '  - **Total budget:** 10,000,000 VND\n'
                '\n'
                '- 💫 **Experience Highlights**\n'
                '  - **Signature moments:** Visiting My Khe Beach, exploring '
                'Marble Mountains, and dining at local vegetarian restaurants.\n'
                '  - **Instagram-worthy locations:** Dragon Bridge at night, '
                'scenic views from Marble Mountains.\n'
                '  - **Cultural immersion:** Local food tours and visits to '
                'traditional markets.\n'
                '\n'
                '---\n'
                '\n'
                '**II. Travel Logistics**\n'
                '\n'
                '- 🛫 **Outbound Journey**\n'
                '  - **Flight Details:**\n'
                '    - **Airline:** Vietravel Airlines\n'
                '    - **Departure:** 6:25 AM on Thu, Oct 2\n'
                '    - **Arrival:** 7:45 AM on Thu, Oct 2\n'
                '    - **Duration:** 1 hr 20 min\n'
                '    - **Price:** 4,870,080 VND\n'
                '  - **Baggage:** Check airline policy for allowances.\n'
                '  - **Airport Transfer:** Arrange transportation to the airport '
                'in Hanoi.\n'
                '\n'
                '- 🛬 **Return Journey**\n'
                '  - **Flight Details:**\n'
                '    - **Airline:** Vietjet\n'
                '    - **Departure:** 5:30 AM on Mon, Oct 6\n'
                '    - **Arrival:** 6:50 AM on Mon, Oct 6\n'
                '    - **Duration:** 1 hr 20 min\n'
                '    - **Price:** 5,561,280 VND\n'
                '  - **Timing Coordination:** Ensure check-out from the homestay '
                'aligns with flight time.\n'
                '\n'
                '---\n'
                '\n'
                '**III. Detailed Daily Itinerary**\n'
                '\n'
                '### Day 1 - Thursday, October 2, 2025\n'
                '\n'
                '- 🌅 **Morning (6 AM - 12 PM)**\n'
                '  - **Wake-up:** 4:30 AM\n'
                '  - **Breakfast:** Light meal at home or grab snacks at the '
                'airport.\n'
                '  - **Flight to Da Nang:** Depart at 6:25 AM, arrive at 7:45 '
                'AM.\n'
                '  - **Transfer to Homestay:** 30-minute taxi ride to Ha Giang '
                'Vegetarian Homestay.\n'
                '\n'
                '- ☀️ **Afternoon (12 PM - 6 PM)**\n'
                '  - **Lunch:** Ngoc Chi Vegetarian Restaurant (12:30 PM)\n'
                '    - **Price Range:** 30,000 – 80,000 VND\n'
                '  - **Activity:** Relax at My Khe Beach (2 PM - 4 PM)\n'
                '    - **Duration:** 2 hours, free entrance.\n'
                '  - **Rest:** Return to homestay for a short break (4 PM - 5 '
                'PM).\n'
                '\n'
                '- 🌙 **Evening (6 PM - onwards)**\n'
                '  - **Dinner:** KURUMI Vegan Restaurant (6:30 PM)\n'
                '  - **Evening Stroll:** Visit Dragon Bridge (8 PM)\n'
                '    - **Duration:** 30 minutes.\n'
                '  - **Return to Homestay:** 8:30 PM.\n'
                '\n'
                '- 🏨 **Accommodation**\n'
                '  - **Property:** Ha Giang Vegetarian Homestay\n'
                '  - **Check-in:** 12 PM\n'
                '  - **Room Type:** Private room with a view.\n'
                '  - **Booking Link:** [Ha Giang Vegetarian '
                'Homestay](https://www.kayak.com/hotels/Ha-Giang-Vegetarian-Homestay,Ha-Giang-p2631332-h1072082236-details/2025-10-02/2025-10-06/2adults?psid=uHCEClmeOr&pm=nightly-base)\n'      
                '\n'
                '- 📝 **Daily Notes**\n'
                '  - **Weather:** Warm, sunny (check forecast closer to date).\n'
                '  - **Dress Code:** Casual beachwear.\n'
                '  - **Local Tips:** Bring sunscreen and a hat for beach '
                'activities.\n'
                '\n'
                '---\n'
                '\n'
                '### Day 2 - Friday, October 3, 2025\n'
                '\n'
                '- 🌅 **Morning (6 AM - 12 PM)**\n'
                '  - **Breakfast:** At homestay (included).\n'
                '  - **Activity:** Visit Marble Mountains (9 AM - 12 PM)\n'
                '    - **Entrance Fee:** 40,000 VND.\n'
                '\n'
                '- ☀️ **Afternoon (12 PM - 6 PM)**\n'
                '  - **Lunch:** Tinh Quan Vegetarian Restaurant (12:30 PM)\n'
                '  - **Activity:** Explore local markets (Con Market) (2 PM - 4 '
                'PM).\n'
                '  - **Rest:** Return to homestay (4 PM - 5 PM).\n'
                '\n'
                '- 🌙 **Evening (6 PM - onwards)**\n'
                '  - **Dinner:** Local street food options (7 PM).\n'
                '  - **Nightlife:** Explore Han River area (8 PM).\n'
                '\n'
                '---\n'
                '\n'
                '### Day 3 - Saturday, October 4, 2025\n'
                '\n'
                '- 🌅 **Morning (6 AM - 12 PM)**\n'
                '  - **Breakfast:** At homestay.\n'
                '  - **Activity:** Day trip to Hoi An (8 AM - 2 PM).\n'
                '    - **Transportation:** Taxi or bus (30 km).\n'
                '\n'
                '- ☀️ **Afternoon (12 PM - 6 PM)**\n'
                '  - **Lunch:** Local eatery in Hoi An (12:30 PM).\n'
                '  - **Explore:** Old Town Hoi An (1 PM - 4 PM).\n'
                '  - **Return to Da Nang (4 PM - 5 PM)**.\n'
                '\n'
                '- 🌙 **Evening (6 PM - onwards)**\n'
                '  - **Dinner:** Back in Da Nang at a local vegetarian '
                'restaurant (7 PM).\n'
                '  - **Evening Activity:** Relax at the homestay or explore '
                'local cafes.\n'
                '\n'
                '---\n'
                '\n'
                '### Day 4 - Sunday, October 5, 2025\n'
                '\n'
                '- 🌅 **Morning (6 AM - 12 PM)**\n'
                '  - **Breakfast:** At homestay.\n'
                '  - **Activity:** Visit Son Tra Peninsula (9 AM - 12 PM).\n'
                '\n'
                '- ☀️ **Afternoon (12 PM - 6 PM)**\n'
                '  - **Lunch:** At a local restaurant (12:30 PM).\n'
                '  - **Activity:** Free time for shopping or beach activities (2 '
                'PM - 5 PM).\n'
                '\n'
                '- 🌙 **Evening (6 PM - onwards)**\n'
                '  - **Dinner:** Farewell dinner at a recommended restaurant (7 '
                'PM).\n'
                '  - **Evening:** Stroll along the beach or relax at the '
                'homestay.\n'
                '\n'
                '---\n'
                '\n'
                '### Day 5 - Monday, October 6, 2025\n'
                '\n'
                '- 🌅 **Morning (6 AM - 12 PM)**\n'
                '  - **Early Breakfast:** At homestay.\n'
                '  - **Check-out:** 4:30 AM for 5:30 AM flight.\n'
                '\n'
                '---\n'
                '\n'
                '**IV. Accommodation Details**\n'
                '\n'
                '- 📍 **Location & Access**\n'
                '  - **Address:** Ha Giang, Vietnam\n'
                '  - **Transport Options:** Taxi to/from airport and '
                'attractions.\n'
                '\n'
                '- 🛎️ **Property Features**\n'
                '  - **Room Type:** Private room with a view.\n'
                '  - **Amenities:** Free breakfast, vegetarian-friendly.\n'
                '\n'
                '- 💰 **Costs & Booking**\n'
                '  - **Nightly Rate:** 240,000 VND\n'
                '  - **Total for 4 nights:** 960,000 VND\n'
                '  - **Booking Link:** [Ha Giang Vegetarian '
                'Homestay](https://www.kayak.com/hotels/Ha-Giang-Vegetarian-Homestay,Ha-Giang-p2631332-h1072082236-details/2025-10-02/2025-10-06/2adults?psid=uHCEClmeOr&pm=nightly-base)\n'      
                '\n'
                '---\n'
                '\n'
                '**V. Curated Experiences**\n'
                '\n'
                '- 🎭 **Activities & Attractions**\n'
                '  - **Marble Mountains:** 40,000 VND entrance fee.\n'
                '  - **My Khe Beach:** Free access.\n'
                '  - **Local Food Tours:** Estimated 500,000 VND.\n'
                '\n'
                '- 🍽️ **Dining Experiences**\n'
                '  - **Ngoc Chi Vegetarian Restaurant:** 30,000 – 80,000 VND.\n'
                '  - **KURUMI Vegan Restaurant:** 60,000 – 130,000 VND.\n'
                '  - **Tinh Quan Vegetarian Restaurant:** 20,000 – 200,000 VND.\n'
                '\n'
                '---\n'
                '\n'
                '**VI. Comprehensive Budget**\n'
                '\n'
                '- 💵 **Total Trip Cost**\n'
                '  - **Grand Total:** 9,140,000 VND\n'
                '  - **Remaining Budget:** 860,000 VND for extras.\n'
                '\n'
                '- 📊 **Detailed Breakdown**\n'
                '  - **Transportation:** 6,000,000 VND\n'
                '  - **Accommodations:** 960,000 VND\n'
                '  - **Activities:** 580,000 VND\n'
                '  - **Food:** 1,600,000 VND\n'
                '\n'
                '---\n'
                '\n'
                '**VII. Essential Information**\n'
                '\n'
                '- 📋 **Pre-Trip Preparation**\n'
                '  - **Visa Requirements:** Check if needed for Vietnam.\n'
                '  - **Health and Insurance:** Ensure travel insurance covers '
                'activities.\n'
                '  - **Packing Recommendations:** Light clothing, swimwear, '
                'sunscreen.\n'
                '\n'
                '- 🗺️ **Destination Guide**\n'
                '  - **Local Customs:** Carry cash, respect temple etiquette.\n'
                '  - **Emergency Contacts:** Local emergency numbers.\n'
                '\n'
                '- 📱 **Digital Resources**\n'
                '  - **Useful Apps:** Grab for transport, Google Maps for '
                'navigation.\n'
                '\n'
                '- ⚠️ **Contingency Plans**\n'
                '  - **Weather Alternatives:** Indoor activities if it rains.\n'
                '  - **Backup Restaurants:** List of nearby eateries.\n'
                '\n'
                '---\n'
                '\n'
                'This itinerary provides a well-structured plan for your '
                'adventure trip from Hanoi to Da Nang, ensuring a balance of '
                'relaxation, exploration, and culinary delights while staying '
                'within your budget. Enjoy your journey! 🌏✈️',)
}